/**
 * AUTO-GENERATED by scripts/calibration/sync-live-calibrations.mjs — 请勿手改。
 * 运行时校准注册表：sceneId → RuntimeSceneCalibration。
 * 缺省场景（未校准）返回 null —— 引擎据此决定不画路线（§31 REPRESENTATIVE 同理）。
 */
import type { RuntimeSceneCalibration } from "../../../types/calibration";
import { CALIBRATION as live_a } from "./live-a-calibration";

/** 全部已同步校准（key = LIVE scene id） */
export const EVEREST_LIVE_CALIBRATIONS: Record<string, RuntimeSceneCalibration> = {
  "live-a": live_a,
};

/** 取某 LIVE 场景的校准（未校准/无校准 → null，调用方据此降级） */
export function calibrationForScene(sceneId: string): RuntimeSceneCalibration | null {
  return EVEREST_LIVE_CALIBRATIONS[sceneId] ?? null;
}
