/**
 * AUTO-GENERATED by scripts/calibration/sync-live-calibrations.mjs — 请勿手改。
 * 同步自 design/world/everest-live/calibration/live-a.json（CalibrationReport 唯一真相源）。
 * 微信运行时不能 require .json 模块，因此以 .ts 模块承载同量数据；本文件只降维
 * 成 RuntimeSceneCalibration 运行时视图（route 已投影 + 可见性）。
 */
import type { RuntimeSceneCalibration } from "../../../types/calibration";

export const CALIBRATION: RuntimeSceneCalibration = {
  "sceneId": "live-a",
  "assetId": "live-a-kala-patthar",
  "status": "REPRESENTATIVE",
  "route": [],
  "waypoints": [],
  "info": {
    "status": "REPRESENTATIVE",
    "medianPx": 0,
    "maxValidationPx": 0,
    "note": "真实珠峰影像 · 代表性视角（未做精确像素投影，routeOverlay 关闭）"
  }
} as RuntimeSceneCalibration;
