"""Emit synthetic DEMO fixture for STAGE-4 occlusion pair test.

独立实现与 tools/.../src/math/occlusion.ts 的 isOccluded 相同的视线步进逻辑
（同一几何定义、各自编码），把一份合成网格 + 一组相机视线 query 落盘成
fixtures/occlusion_pair.json。TS 侧 tests/occlusion-pair.test.ts 读同一 fixture，
用 occlusion.ts 独立跑一遍并断言 100% 一致 —— 这份 fixture 是双方共有的“粘胶”。

运行： python3 scripts/live/occlusion_pair_fixture.py
输出： scripts/live/fixtures/occlusion_pair.json
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

RNG_SEED = 20243909
OUT_DIR = Path(__file__).parent / "fixtures"
OUT_JSON = OUT_DIR / "occlusion_pair.json"
OUT_TS = OUT_DIR / "occlusion_pair.ts"

# ruff/opengrep 规则要求可抛异常调用包进 try —— 集中到带 try 的 helper，
# 业务代码一律走 helper（保证与 TS oc地址单元步进一致）。
def _to_float(v: float | int | np.generic | str | bytes) -> float:
    try:
        return float(v)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"non-numeric: {v!r}") from exc


def to_int_floor(v: float) -> int:
    try:
        return int(math.floor(v))
    except (TypeError, ValueError, OverflowError) as exc:
        raise ValueError(f"non-integer: {v!r}") from exc


def ts_round(v: float) -> int:
    """TS Math.round 语义（正数 floor(v+0.5)，负数 ceil(v-0.5)）。"""
    if v >= 0.0:
        return to_int_floor(v + 0.5)
    return to_int_floor(math.ceil(v - 0.5))


def synthetic_grid(rows: int, cols: int) -> np.ndarray:
    """合成网格 —— 公式与 occlusion.ts 测试重建时完全一致（含 seed）。"""
    rng = np.random.default_rng(RNG_SEED)
    rr = np.arange(rows)[:, None]
    cc = np.arange(cols)[None, :]
    noise = rng.normal(0.0, 6.0, size=(rows, cols))
    ridge = 1500.0 * np.exp(-(((rr - 26) / 18.0) ** 2 + ((cc - 40) / 120.0) ** 2))
    peak = 900.0 * np.exp(-(((rr - 70) / 11.0) ** 2 + ((cc - 88) / 9.0) ** 2))
    swell = 220.0 * np.sin(cc / 23.0) * np.cos(rr / 17.0)
    return (ridge + peak + swell + noise).astype(np.float32)


def nearest_elev(grid: np.ndarray, step: float, x: float, y: float) -> float | None:
    """世界点 → 最近 cell 的 z（与 occlusion.ts worldToCell + grid.z 一致）。"""
    col = ts_round(x / step)
    row = ts_round(y / step)
    rows, cols = grid.shape
    if row < 0 or row >= rows or col < 0 or col >= cols:
        return None
    return _to_float(grid[row, col])


def is_occluded(
    grid: np.ndarray, step: float,
    cam: np.ndarray, target: np.ndarray,
) -> bool:
    """与 occlusion.ts isOccluded 一一对应的视线步进。cam/target 为 (x,y,z)。"""
    dx, dy, dz = target - cam
    dist_xy = math.hypot(dx, dy)
    if dist_xy < step:
        return False
    steps = max(2, math.ceil(dist_xy / (step * 0.5)))
    for s in range(1, steps):
        t = s / steps
        px = cam[0] + dx * t
        py = cam[1] + dy * t
        pz = cam[2] + dz * t
        elev = nearest_elev(grid, step, px, py)
        if elev is None:
            continue
        dist_to_cam = math.hypot(px - cam[0], py - cam[1])
        if dist_to_cam < step:
            continue
        if elev > pz + 0.5:
            return True
    return False


def main() -> None:
    rows, cols, step = 96, 128, 100.0
    rng = np.random.default_rng(RNG_SEED + 1)
    grid = synthetic_grid(rows, cols)
    cams = [
        np.array([-2600.0, 500.0, 0.0]),       # 西北低处
        np.array([1800.0, 300.0, 0.0]),       # 正北低处
        np.array([8200.0, 400.0, 0.0]),        # 东侧低处
        np.array([900.0, 5600.0, 1800.0]),     # 高处走廊（山顶中段）
    ]
    targets: list[tuple[float, float, float]] = []
    for _ in range(48):
        targets.append((
            _to_float(rng.uniform(1000.0, 9000.0)),
            _to_float(rng.uniform(1500.0, 9000.0)),
            _to_float(rng.uniform(-300.0, 1800.0)),
        ))
    queries = []
    for cam in cams:
        for tgt in targets:
            cam_a = np.asarray(cam, dtype=np.float64)
            tgt_a = np.asarray(tgt, dtype=np.float64)
            queries.append({
                "camera": [_to_float(v) for v in cam],
                "target": [_to_float(v) for v in tgt],
                "expected": bool(is_occluded(grid, step, cam_a, tgt_a)),
            })

    fixture = {
        "schema": "occlusion-pair/v1",
        "note": "synthetic ridge + peak + noise; 4 cameras × 48 targets; step=100m",
        "grid": {
            "rows": rows,
            "cols": cols,
            "step": step,
            "z": [
                _to_float(c)
                for row in grid.tolist()
                for c in row
            ],
        },
        "queries": queries,
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(fixture, indent=1), encoding="utf-8")
    # TS 侧以 .ts 模块消费同一对象（Gate 3.1 禁止 test import .json）；
    # 两份由同一生成脚本同时写出 → 永不漂移。
    OUT_TS.write_text(
        "// @generated by scripts/live/occlusion_pair_fixture.py —— 与 occlusion_pair.json 同源，勿手改。\n"
        f"const fixture: unknown = {json.dumps(fixture)};\nexport default fixture;\n",
        encoding="utf-8",
    )
    hits = sum(1 for q in queries if q["expected"])
    print(f"OK {len(queries)} queries, {hits} occluded, grid {rows}×{cols} → {OUT_JSON} / {OUT_TS}")


if __name__ == "__main__":
    main()
